# Generated by Django 4.2 on 2024-03-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('memo', models.TextField(max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('journal_icon', models.ImageField(upload_to='static/uploads/journal_icons')),
            ],
        ),
    ]
