# Generated by Django 4.2 on 2024-04-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_icon',
            field=models.ImageField(default='defaults/journal_icon.svg', upload_to='uploads/journal_icons'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_app.journal')),
            ],
        ),
    ]
