# Generated by Django 4.2 on 2024-04-19 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prose.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=prose.fields.RichTextField(),
        ),
    ]
