# Generated by Django 4.2 on 2024-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0002_alter_journal_journal_icon_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
