# Generated by Django 4.2 on 2024-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_alter_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
