# Generated by Django 4.2 on 2024-04-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_journal_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='latest_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journal_app.post'),
        ),
    ]
